### ISSUE TITLE
To be able to link to the url of a particular version of a project

### ISSUE THREAD

**Issue by philibe** [pmsipilot/PSIHplan#28]
Actuellement on a un lien vers l'ensemble des versions d'un projet. ça serait bien de pouvoir copier-coller un lien qui pointe vers une version particulière d'un projet.

Le top serait avec la réécriture d'url (issue #27)

**Comment by youknowriad** [comment]
je comprend pas l'intérêt d'avoir ça, ça servirait à quoi cette page ?

**Comment by philibe** [comment]
En fait pour communiquer/parler d'une release en particulier d'un sous projet à partir de l'url. Par exemple je veux parler de la release 13.5.12 à quelqu'un, actuellement quand il reçoit l'url il doit se coltiner la liste de toute les releases du sous-projet. 

A défaut d'un lien n'affichant que la release sélectionné, au moins un tri par project version et une ancre sur chaque ligne de project version. :)
