### ISSUE TITLE
Reprendre la description des features de chaque projet dans la vue board

### ISSUE THREAD

**Issue by jubianchi** [pmsipilot/PSIHplan#37]
Afin que les utilisateurs non-connectés puisse voir ce qui va être inclu dans les releases à venir, il serait intéressant d'afficher, en dessous des barres de progression un encart contenant le récapitulatif des features logicielles qui vont être livrées.

Dans l'idéal, il faudrait masqué cet encart par défaut et proposer un petit bouton/lien pour l'afficher afin que la vue board ne soit pas surchargée.

**Comment by wixyvir** [comment]
close?
