### ISSUE TITLE
Ajouter un bouton pour supprimer une release

### ISSUE THREAD

**Issue by grib0** [pmsipilot/PSIHplan#5]
L'API permet de supprimer une release, il manque le bouton associé dans la gui

**Comment by wixyvir** [comment]
Je suis contre, si on ne livre pas un projet pour une livraison de plateforme, c'est qu'on le fera pour une autre version de plateforme. L'édition suffit, sauf si le projet n'est plus jamais livré.

On pourra ajouter ce bouton si on ajoute aussi une notion de permissions.

Close ?
